// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "todo.get", input: number, result: Task } | 
        { key: "todo.get_all", input: never, result: Task[] },
    mutations: 
        { key: "todo.create", input: CreateTodoArgs, result: Task } | 
        { key: "todo.delete", input: DeleteTodoArgs, result: boolean } | 
        { key: "todo.update", input: UpdateTodoArgs, result: Task },
    subscriptions: never
};

export type DeleteTodoArgs = { id: number }

export type TaskStatus = "Undone" | "Done"

export type UpdateTodoArgs = { id: number; title: string; status: TaskStatus }

export type Task = { id: number; title: string; status: TaskStatus }

export type CreateTodoArgs = { title: string; status: TaskStatus }
