// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "todo.get", input: number, result: Task },
    mutations: never,
    subscriptions: never
};

export type TaskStatus = "Undone" | "Done"

export type Task = { id: number; title: string; status: TaskStatus }
